version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: rdbr-assignment_app
    depends_on:
      - postgres
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - rdbr-assignment-network

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: rdbr-assignment_postgres
    tty: true
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data/
    networks:
      - rdbr-assignment-network

  nginx:
    image: nginx:alpine
    container_name: rdbr-assignment_nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - "${APP_PORT}:8001"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - rdbr-assignment-network

networks:
  rdbr-assignment-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
